require("mason").setup()

capabilities = require('cmp_nvim_lsp').default_capabilities()
on_attach = function(client, bufnr)
    vim.keymap.set('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>')
    vim.keymap.set('n', 'gf', '<cmd>lua vim.lsp.buf.format({async = true})<CR>')
    vim.keymap.set('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>')
    vim.keymap.set('n', 'gn', '<cmd>lua vim.lsp.buf.rename()<CR>')
    vim.keymap.set('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>')
    vim.keymap.set('i', '<C-j>', '<Plug>(skkeleton-enable)')
    vim.keymap.set('c', '<C-j>', '<Plug>(skkeleton-enable)')
end

require('lsp.bash')
require('lsp.fsharp')
require('lsp.lua')
require('lsp.python')
require('lsp.rust')
require('lsp.satysfi')
require('lsp.vue')
