"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true


#[time]
#disabled = false
#format = '🕙 [\[ $time \]]($style) '
#time_format = '%T'
#utc_time_offset = '+9'
#time_range = '10:00:00-14:00:00'
