grammar = [
    {name = "satysfi", source = {git = "https://github.com/monaqa/tree-sitter-satysfi.git", rev ="5519c547418ecb31ac7d63e64653aed726b5d1c3" }},
    {name = "moonbit", source = {git = "https://github.com/moonbitlang/tree-sitter-moonbit.git", rev ="f4b3ecc298b13192ff0dafa295b0078d000e5931" }}
]

[language-server]
ruff = { command = "ruff", args = ["server"]}
ty = { command = "ty", args = ["server"]}
qmlls = { command = "qmlls"}
tinymist = { command = "tinymist", config = { exportPdf = "onType", rootFile = "main.typ"}}
satysfi-language-server = { command = "satysfi-language-server"}
moonbit-lsp = { command = "moonbit-lsp" }
steel-language-server = { command = "steel-language-server" }
texlab = { config.texlab = { build = { executable = "latexmk", args = ["%f"], onSave = true, forwardSearchAfter = true, pdfDirectory = "out" }, forwardSearch = { executable = "zathura", args = ["--synctex-forward", "%l:1:%f", "%p"] }, chktex.onEdit = true } }

oxlint = { command = "oxlint", args = ["--lsp"]}
oxfmt = { command = "oxfmt", args = ["--lsp"]}
tailwindcss-lsp = { command = "tailwindcss-language-server", args = ["--stdio"]}
unocss-language-server = { command = "unocss-language-server", args = ["--stdio"]}
biome = { command = "biome", args = ["lsp-proxy"]}
vue-language-server = { command = "vue-language-server", args = ["--stdio"], config.typescript.tsdk = "node_modules/typescript/lib" }
typescript-language-server = { command = "typescript-language-server", args = ["--stdio"], config.hostInfo = "helix", required-root-patterns = ["package.json"] }
vtsls = { command = "vtsls", args = ["--stdio"],  config.hostInfo =   "helix", config.vtsls.tsserver.globalPlugins = [ { name = "@vue/typescript-plugin", location = "/home/itt/.local/share/mise/installs/npm-vue-language-server/latest/lib/node_modules/@vue/language-server", languages = ["vue"], configNamespace = "typescript" }] }
deno-lsp ={ command = "deno", args = ["lsp"], required-root-patterns = ["deno.json"], config.deno.enable = true }

[[language]]
name = "vue"
language-servers = [
  "vtsls",
  # "vue-language-server",
  # "vscode-html-language-server",
  # "vscode-css-language-server",
  "unocss-language-server",
  # "tailwindcss-ls",
  # "biome"
]

[[language]]
name = "javascript"
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = [
  "vtsls",
  "deno-lsp",
  # "biome"
]
auto-format = true
[[language]]
name = "typescript"
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = [
  "vtsls",
  "deno-lsp",
  # "biome"
]
auto-format = true

[[language]]
name = "html"
auto-format = true
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  "unocss-language-server",
  "biome",
]

[[language]]
name = "css"
auto-format = true
language-servers = [
  "vscode-css-language-server",
  "tailwindcss-ls",
  "unocss-language-server",
  # "biome"
]

[[language]]
name = "scss"
auto-format = true
language-servers = ["vscode-css-language-server", "tailwindcss-ls", "biome"]

[[language]]
name = "jsx"
auto-format = true
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "svelte"
auto-format = true
language-servers = ["svelteserver", "tailwindcss-ls"]

[[language]]
name = "python"
language-servers = ["ruff", "ty", "pyright", "pylsp"]
auto-format = true

[[language]]
name = "typst"
auto-format = true
indent = { tab-width = 2, unit = "  "}

[[language]]
name = "satysfi"
scope = "source.satysfi"
file-types = ["saty", "satyh", "satyg"]
roots = []
auto-format = false
comment-tokens = ["%"]
block-comment-tokens = []
language-servers = ["satysfi-language-server"]
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "scheme"
auto-format = true
language-servers = ["steel-language-server"]

[[language]]
name = "moonbit"
scope = "source.moonbit"
injection-regex = "moonbit"
file-types = ["mbt"]
comment-token = "//"
block-comment-tokens = []
language-servers = ["moonbit-lsp"]
indent = { tab-width = 2, unit = "  " }


[[language]]
name = "qml"
language-servers = ["qmlls"]

